# Data-analytiikan osaaja

# Koulutus: 30.10.-1.11.2019

# Aihe: luokittelu


Tässä harjoituksessa tutustumme lähimmän naapurin luokittelijaan (k nearest neighbor classification).

Luokitteluongelma on ohjattua oppimista, eli tarvitsemme syötedatan lisäksi myös vastemuuttujaksi tunnetun luokkkatiedon.

Scikit-learn -kirjasto sisältää paljon vaihtoehtoja, tänään tutustumme k lähimmän naapurin luokittelijaan. K on luokittelijan paramateri, sillä valitaan kuinka moneen lähimpään naapuriin uutta, luokiteltavaa dataa verrataan. Yksinkertaisimmillaan k = 1.

In [1]:
# Otetaan käyttöön tarvittavat kirjastot
import numpy as np
import matplotlib.pyplot as plt

from sklearn import neighbors, datasets

Ensimmäiseksi käytämme scikit-learn kirjastossa valmiina olevaa datajoukkoa, joka määrittelee luokitteluongelman.

Ladataan Iris -datajoukko, tarkempi historia liittyen datajoukkoon löytyy Wikipediasta: https://en.wikipedia.org/wiki/Iris_flower_data_set

In [2]:
# Ladataan iris -datajoukko:
from sklearn.datasets import load_iris

(iris_X, iris_luokka) = load_iris(return_X_y=True)

# iris_X
# iris_luokka

len(iris_luokka)

150

Harjoitus 1. Katso syötedataa X, montako muuttujaa siinä on? Katso vastemuuttujaa luokka, montako luokkaa ongelmassa on?

In [19]:
iris_X.shape

(150, 4)

In [20]:
# Luodaan ensin luokittelija:
luokittelija = neighbors.KNeighborsClassifier(n_neighbors=1)

# Opetetaan luokittelija data-aineistolla:
luokittelija.fit(iris_X, iris_luokka)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Nyt voimme käyttää luokittelijaa datan luokitteluun. Luokittellaan vaikka aineiston ensimmäinen iris:

In [21]:
# Ensimmäinen data, syötemuuttuja:
eka_X = iris_X[1,:]
print(eka_X)

[4.9 3.  1.4 0.2]


In [22]:
# ensimmäinen data, vastemuuttuja:
eka_luokka = iris_luokka[1]
print(eka_luokka)

0


In [23]:
# Katsotaan mikä luokka saadaan ekalla datalla:
luokittelija.predict([[4.9, 3.0, 1.4, 0.2]])

array([0])

Voimme laskea opetusvirheen luokittelemalla aineiston ja vertailemalla ennustettuja luokkia vastemuuttujiin, koska ne on opetusaineistossa tunnettu.

In [24]:
# Ennustetaan opetusjoukon avulla 
ennustettu_luokka = luokittelija.predict(iris_X)

In [25]:
# ymmärrä miten virhe (tai oikein luokitellut) lasketaan:
oikein_luokitellut = np.sum(ennustettu_luokka == iris_luokka)
print(oikein_luokitellut)

150


In [26]:
# Tai sama oikeinluokittelu prosentteina:
oikein_luokitellut = np.sum(ennustettu_luokka == iris_luokka) /len(iris_luokka)
print(oikein_luokitellut)

1.0


In [27]:
# Tai virhe prosentteina:
väärin_luokitellut = 1 - oikein_luokitellut
print(väärin_luokitellut)

0.0


Onneksi olkoon! Kaikki luokiteltiin oikein! Tai hetkinen..

Miksi oli helppoa saada kaikki oikein opetusjoukossa kun käytettiin 1 lähimmän naapurin luokittelijaa? Onko luokittelutulos ennsutettavissa pelkän asetelman perusteella (on, mutta mieti miksi!)

Tehtävä 2. Vaihda luokittelijaa 3 lähimään naapurin luokittelijaksi. Katso miten opetusjoukon virhe muuttuu.

In [32]:
luokittelija2 = neighbors.KNeighborsClassifier(n_neighbors = 3)
luokittelija2.fit(iris_X, iris_luokka)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [33]:
print(eka_X)

[4.9 3.  1.4 0.2]


In [35]:
luokittelija2.predict([[4.9,3.0,1.4,0.2]])

array([0])

In [40]:
ennustettu_luokka2 = luokittelija2.predict(iris_X)

In [60]:
oikein_luokitellut2 = np.sum(ennustettu_luokka2 == iris_luokka)
print(oikein_luokitellut2)

144


In [61]:
oikein_luokitellut2_suhde = np.sum(ennustettu_luokka2 == iris_luokka)/len(iris_luokka)
print(oikein_luokitellut_suhde)

0.96


In [62]:
vaarin_luokitellut2_suhde = 1 - oikein_luokitellut_suhde
print(vaarin_luokitellut_suhde)

0.040000000000000036


Tehtävä 3. Vaihda datajoukkoa luokitteluongelmassa. Tutustu mitä datajoukkoja on saatavilla scikit-learn -kirjastossa tai ota joku luokitteluongelma UCI dataluettelosta, john tutustuimme eilen:
https://archive.ics.uci.edu/ml/index.php

In [47]:
from sklearn.datasets import load_wine

wine_X, wine_luokka = load_wine(return_X_y=True)

In [48]:
print(wine_X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [49]:
print(wine_luokka)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [51]:
wine_X.shape

(178, 13)

In [52]:
wine_luokka.shape

(178,)

In [54]:
luokittelija3 = neighbors.KNeighborsClassifier(n_neighbors=3)
luokittelija3.fit(wine_X, wine_luokka)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [55]:
eka3_X = wine_X[1,:]
print(eka3_X)

[1.32e+01 1.78e+00 2.14e+00 1.12e+01 1.00e+02 2.65e+00 2.76e+00 2.60e-01
 1.28e+00 4.38e+00 1.05e+00 3.40e+00 1.05e+03]


In [57]:
eka_luokka3 = wine_luokka[1]
print(eka_luokka3)

0


In [56]:
luokittelija3.predict([eka3_X])

array([0])

In [58]:
ennustettu_luokka3 = luokittelija3.predict(wine_X)

In [59]:
oikein_luokitellut3 = np.sum(ennustettu_luokka3 == wine_luokka)
print(oikein_luokitellut3)

155


In [63]:
oikein_luokitellut3_suhde = np.sum(ennustettu_luokka3 == wine_luokka)/len(wine_luokka)
print(oikein_luokitellut3_suhde)

0.8707865168539326


In [64]:
vaarin_luokitellut3_suhde = 1 - oikein_luokitellut3_suhde
print(vaarin_luokitellut3_suhde)

0.1292134831460674


In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X_train, X_test, y_train, y_test = train_test_split(wine_X, wine_luokka, test_size=0.33, random_state=42)

In [67]:
luokittelija4 = neighbors.KNeighborsClassifier(n_neighbors=3)
luokittelija4.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [68]:
ennustettu_luokka4 = luokittelija4.predict(X_test)

In [70]:
oikein_luokitellut4 = np.sum(ennustettu_luokka4 == y_test)
print(oikein_luokitellut4)

41


In [72]:
oikein_luokitellut4_suhde = np.sum(ennustettu_luokka4 == y_test)/len(y_test)
print(oikein_luokitellut4_suhde)

0.6949152542372882


In [74]:
vaarin_luokitellut4_suhde = 1 - oikein_luokitellut4_suhde
print(vaarin_luokitellut4_suhde)

0.30508474576271183


In [76]:
len(y_test)

59