# Data-analytiikan osaaja

# Koulutus: 30.10.-1.11.2019

# Aihe: data


Harjoitus 1. Lue tekstitiedosto numbers.txt Numpy-taulukkoon 

In [4]:
import numpy as np

numbers1 = np.loadtxt("numbers.txt")
print(numbers)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


Harjoitus 2. Lue csv-tiedosto numbers2.csv Numpy-taulukkoon

In [6]:
numbers2 = np.genfromtxt("numbers2.csv", delimiter=",")
print(numbers2)

[[2.5  3.6  7.6 ]
 [1.3  1.56 1.99]
 [ nan 6.28 9.42]]


Harjoitus 3. Lue csv-tiedosto salary.csv Pandas-taulukkoon

In [8]:
import pandas as pd

salary = pd.read_csv("salary.csv")
print(salary)

   Adam  1300
0   Eve  1300
1  John  2300
2  Mary  4500


Harjoitus 4. Lue csv-tiedosto hr.csv Pandas-taulukkoon

In [9]:
hr = pd.read_csv("hr.csv")
print(hr)

  Person   Department           Title  Salary
0   Adam           HR    HR secretary    1200
1    Eve        Sales  Sales director    2400
2   John  Engineering      Programmer    6800
3   Mary          NaN             CEO    6900


Harjoitus 5. Lue Excel-taulukko cities.xlsx ja katso mitä taulukossa on

In [29]:
cities = pd.read_excel("cities.xlsx", header=None)
print(cities)

            0  1
0   Stockholm -1
1    Helsinki -6
2  Copenhagen -2
3        Oslo  0


Harjoitus 6. Lue JSON-tiedosto songs.json ja katso kenttien sisältöä

In [11]:
songs = pd.read_json("songs.json")
print(songs)

            endTime        artistName                               trackName  \
0  2019-03-03 20:24         Kraftwerk      Autobahn - 2009 Remastered Version   
1  2019-03-03 20:24       David Bowie  Battle for Britain (The Letter) - Live   
2  2019-02-27 13:42  Vesa-Matti Loiri                    Mieleni minun tekevi   
3  2019-03-06 19:07         J.J. Cale                              City Girls   

   msPlayed  
0    357802  
1       725  
2     28693  
3    169598  


Harjoitus 7. Luo relaatiotietokanta haluamallasi työkalulla ja lue se (jokeritehtävä)

In [12]:
import sqlite3

In [13]:
connection = sqlite3.connect("test.db")

In [14]:
c = connection.cursor()

In [15]:
c.execute('''CREATE TABLE TEST
             ([generated_id] INTEGER PRIMARY KEY, [Person] text, [Department] Text, [Title] text, [Salary] integer)''')

In [16]:
connection.commit()

In [17]:
read_hr = pd.read_csv("hr.csv")
read_hr.to_sql('TEST', connection, if_exists='append', index = False)

In [18]:
read_hr.head()

Person   Department           Title  Salary
0   Adam           HR    HR secretary    1200
1    Eve        Sales  Sales director    2400
2   John  Engineering      Programmer    6800
3   Mary          NaN             CEO    6900

In [28]:
for row in c.execute('SELECT * FROM TEST'):
    print(row)

(1, 'Adam', 'HR', 'HR secretary', 1200)
(2, 'Eve', 'Sales', 'Sales director', 2400)
(3, 'John', 'Engineering', 'Programmer', 6800)
(4, 'Mary', None, 'CEO', 6900)
