# Data-analytiikan osaaja

# Koulutus: 30.10.-1.11.2019

# Aihe: data


Harjoitus 1. Lue tekstitiedosto numbers.txt Numpy-taulukkoon 

In [2]:
import numpy as np

numbers = np.loadtxt("numbers.txt")
print(numbers)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


Harjoitus 2. Lue csv-tiedosto numbers2.csv Numpy-taulukkoon

[[2.5  3.6  7.6 ]
 [1.3  1.56 1.99]
 [ nan 6.28 9.42]]


Harjoitus 3. Lue csv-tiedosto salary.csv Pandas-taulukkoon

In [1]:
# Ratkaisu tehtävään 3 tähän



Adam  1300
0   Eve  1300
1  John  2300
2  Mary  4500

Harjoitus 4. Lue csv-tiedosto hr.csv Pandas-taulukkoon

In [10]:
# Ratkaisu tehtävään 4 tähän



Person   Department           Title  Salary
0   Adam           HR    HR secretary    1200
1    Eve        Sales  Sales director    2400
2   John  Engineering      Programmer    6800
3   Mary          NaN             CEO    6900

Harjoitus 5. Lue Excel-taulukko cities.xlsx ja katso mitä taulukossa on

In [8]:
# Ratkaisu tehtävään 5 tähän



0  1
0   Stockholm -1
1    Helsinki -6
2  Copenhagen -2
3        Oslo  0

Harjoitus 6. Lue JSON-tiedosto songs.json ja katso kenttien sisältöä

In [14]:
# Ratkaisu tehtävään 6 tähän



artistName           endTime  msPlayed  \
0         Kraftwerk  2019-03-03 20:24    357802   
1       David Bowie  2019-03-03 20:24       725   
2  Vesa-Matti Loiri  2019-02-27 13:42     28693   
3         J.J. Cale  2019-03-06 19:07    169598   

                                trackName  
0      Autobahn - 2009 Remastered Version  
1  Battle for Britain (The Letter) - Live  
2                    Mieleni minun tekevi  
3                              City Girls

Harjoitus 7. Luo relaatiotietokanta haluamallasi työkalulla ja lue se (jokeritehtävä)

In [ ]:
# Ratkaisu tehtävään 7 tähän

# Tämä tehtävä edellyttää aiempaa kokemusta